folio-org/jenkins-pipeline-libs

vars/sonarqubeScanNPM.groovy
exclude *.test.js files for FOLIO-2449
=> exclude *.test.js files for FOLIO-2449

vars/deployTenantK8.groovy
adds option to turn off sample data loading in k8s tenant deploy
=> Folio 2336 snap

resources/org/folio/getOkapiToken.sh, src/org/folio/foliociCommands.groovy, vars/setupPreviewEnv.groovy
New pipelines to support PR preview mode.
=> Folio 2011a

vars/buildMvn.groovy, vars/kubeDeploy.groovy
Reverts folio-org/jenkins-pipeline-libs#78
=> Revert "add param for okapi url"

resources/org/folio/dockerHubPublishMetadata.sh, vars/buildJavaDocker.groovy
See [FOLIO-2541](https://issues.folio.org/browse/FOLIO-2541)
=> FOLIO-2541 fix push docker hub minimal readme

resources/org/folio/preview-tenant-cleanup.py, resources/org/folio/requirements.txt, vars/moduleCleanup.groovy, vars/previewTenantCleanup.groovy
Adds script to clean up pr preview tenants when PRs are closed.
=> Folio 2534 tenant cleanup

vars/runTestNPM.groovy
set NODE_OPTIONS prior to running unit tests.  See FOLIO-2638.
=> Node mem test allocation

vars/buildNPM.groovy
See [FOLIO-2674](https://issues.folio.org/browse/FOLIO-2674)
Tested with a branch of ui-courses which uses Cypress, and with ui-checkout which does not yet.
=> FOLIO-2674 Save artifacts of Cypress for front-end tests

vars/buildNPM.groovy, vars/runTestNPM.groovy
See [FOLIO-2674](https://issues.folio.org/browse/FOLIO-2674)
=> FOLIO-2674 Only archive cypress on failure

vars/runNPMScript.groovy, vars/runTestNPM.groovy
See [FOLIO-2674](https://issues.folio.org/browse/FOLIO-2674)
=> FOLIO-2674 Archive cypress on failure, show screenshots for failed tests

vars/buildNPM.groovy, vars/sonarqubeScanNPM.groovy
=> FOLIO-2682 sonarqube alternative LCOV path

vars/buildMvn.groovy, vars/setEnvMvn.groovy
Set java install based on presense of java-11 directory. Plus free white space cleanup from vim.
=> Folio 2637 java 11 agent

vars/buildNPM.groovy, vars/runTestNPM.groovy
=> FOLIO-2810 

vars/buildMvn.groovy, vars/sonarqubeMvn.groovy
Update Sonarqube scanner and add 'clean' phase before 'deploy' in Maven build pipeline
=> Folio 2935 maven deploy

vars/buildNPM.groovy, vars/sonarqubeScanNPM.groovy
Configure specific top-level project directories as the "root" directories for Sonarqube Scans.
=> FOLIO-2920 

src/org/folio/foliociCommands.groovy, vars/buildNPM.groovy, vars/setEnvNPM.groovy
add some operations to get the author of last commit. Skip unit tests if last comitter is 'FOLIO Translations bot'
=> FOLIO-2972

vars/buildDocker.groovy
Added "Publish Readme Docker Hub" for jenkins-pipeline-libs/vars/buildDocker.groovy.
Tested: https://hub.docker.com/r/folioci/mod-remote-storage
=> Folio 2916 Publish Readme Docker Hub

resources/org/folio/collect-logs.sh
=> FOLIO-2979 

vars/buildDocker.groovy, vars/buildJavaDocker.groovy
=> Update Docker build functions to allow building from "main" as well as "master"

vars/buildMvn.groovy, vars/buildNPM.groovy
Crude. If useful, then improve.
=> FOLIO-3189 Show Jenkins env BRANCH_IS_PRIMARY

src/org/folio/foliociCommands.groovy, vars/buildMvn.groovy, vars/buildNPM.groovy, vars/setEnvMvn.groovy, vars/setEnvNPM.groovy
and use it in setEnvMvn and setEnvNPM
=> FOLIO-3189 Add function isBranchPrimary

src/org/folio/foliociCommands.groovy, vars/buildMvn.groovy, vars/buildNPM.groovy, vars/setEnvMvn.groovy, vars/setEnvNPM.groovy
Shown in Checkout stage of Maven and NPM build pipelines and used in their deploy and publish stages.
=> FOLIO-3189 verify use of Jenkins env.BRANCH_IS_PRIMARY

vars/buildDocker.groovy, vars/buildJavaDocker.groovy, vars/buildMvn.groovy, vars/buildNPM.groovy, vars/sonarqubeMvn.groovy, vars/sonarqubeMvn_report.groovy, vars/sonarqubeScanNPM.groovy
Utilised in build Stages for Sonar and Docker.
Verified in branch builds for mod-notes and ui-checkin repos.
=> FOLIO-3224 Use env.BRANCH_IS_PRIMARY to decide which branch

vars/buildNPM.groovy
=> FOLIO-3184 Restore one bracket

vars/buildMvn.groovy, vars/runApiLint.groovy
Add option apiWarnings to treat warnings as errors
=> FOLIO-3382: buildMvn and api-lint: new option for warnings

README.md
https://issues.folio.org/browse/FOLIO-3407
=> healthChkCmd: Prefer wget over curl

vars/platformDepCheck.groovy
Make sure we are using the latest okapi snapshot for interface dependency check step.
=> Pull latest okapi from folioci docker repo

vars/buildMvn.groovy, vars/setEnvMvn.groovy
- Add support for Java 21.
- Make Java 17 the default (changed from Java 11)
=> FOLIO-4054

vars/buildMvn.groovy, vars/setEnvMvn.groovy
Modify Maven build pipelines to be in sync with Maven pipelines on master branch and support Java 21 build image.
=> update maven build pipelines to support Java 21
